name: OpenNews
description: The website for OpenNews
url: https://www.opennews.org
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
plugins:
  - jekyll-redirect-from
exclude: ['*.yml']
permalink: /blog/:title/
future: true
