name: OpenNews
description: The website for OpenNews
url: https://www.opennews.org
markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
plugins:
  - jekyll-redirect-from
exclude: ['*.yml']
permalink: /blog/:title/
future: true

defaults:
  - scope:
      path: ""
    values:
      excerpt: ""
      description: OpenNews connects a network of developers, designers, journalists, and editors to collaborate on open technologies and processes within journalism. Alongside our community, our mission includes fighting for a future where newsrooms are anti-racist, equitable, inclusive, and collaborative.
