markdown: rdiscount
permalink: /blog/:title/
name: OpenNews
description: The blog for OpenNews
url: https://www.opennews.org
future: true
rdiscount:
  extensions: [smart]
gems:
  - jekyll-redirect-from
