markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
permalink: /blog/:title/
name: OpenNews
description: The blog for OpenNews
url: https://www.opennews.org
future: true
rdiscount:
  extensions: [smart]
gems:
  - jekyll-redirect-from
